### ISSUE TITLE
can't load package 'regex'

### ISSUE THREAD

**Issue by stereobooster** [ponylang/regex#18]
To reproduce

```
git clone https://github.com/stereobooster/pony-lisp.git
cd pony-lisp
make docker-build-image
make docker-build
```

Result
```
stable env ponyc  lisp/test -o build/release
...
Error:
regex: couldn't locate this path
Error:
/src/main/lisp/parser.pony:1:1: can't load package 'regex'
use "regex"
^
Error:
/src/main/lisp/test/tokenizer.pony:2:1: can't load package '..'
use ".."
^
Makefile:37: recipe for target 'build/release/test' failed
make: *** [build/release/test] Error 1
```

**Comment by SeanTAllen** [comment]
Hi @stereobooster,

you need to do `stable fetch` to fetch the dependencies before you do `stable env`.

**Comment by stereobooster** [comment]
Hi,

It is done in Dockerfile:

```
FROM ponylang/ponyc

...

COPY bundle.json ./
RUN stable fetch
```

but I can move it to makefile 🤔

**Comment by SeanTAllen** [comment]
@stereobooster move it to the Makefile and let me know what happens.

**Comment by stereobooster** [comment]
Yes it helped. I have no idea what is the difference, though.

Thanks for help.

**Comment by SeanTAllen** [comment]
@stereobooster `stable fetch` needs to be executed from the root of your project. I would guess that it isn't being executed from there when the Docker image is building. Just a guess. Good luck!
